service: testing-project

frameworkVersion: "=1.27.3"

provider:
  name: aws
  runtime: nodejs8.10
  region: sa-east-1
  memorySize: 128
  timeout: 30
  environment:
    DYNAMODB_REGION: sa-east-1
    DYNAMODB_ENDPOINT: http://localhost:8000
    DYNAMODB_READ_UNITS: 1
    DYNAMODB_WRITE_UNITS: 1
    
functions:

  createCampaign:
    handler: src/functions/campaigns/create.handler
    events:
      - http:
          path: /campaigns
          method: post
          cors: true
  
  searchCampaigns:
    handler: src/functions/campaigns/search.handler
    events:
      - http:
          path: /campaigns
          method: get
          cors: true

plugins:
  - serverless-offline
